### ISSUE TITLE
Użycie raportu

### ISSUE THREAD

**Issue by AdrianHarenczyk** [boczkas/assertTest#13]
https://github.com/boczkas/assertTest/blob/301c182092902f86936d182929e8fe5a3555151b/src/test/java/TestArrayList.java#L23

Fajne użycie raportu jako jednej metody, zamiast wywoływania asercji za każdym razem osobno, jednak przy późniejszym rozwoju przeszkodzi w implementacji testowania metod pojedynczo.

**Comment by boczkas** [comment]
Dzięki
