### ISSUE TITLE
unnecessary space

### ISSUE THREAD

**Issue by JaroslawSlaby** [boczkas/assertTest#16]
https://github.com/boczkas/assertTest/blob/301c182092902f86936d182929e8fe5a3555151b/src/test/java/TestArrayList.java#L993

Delete.

**Comment by JaroslawSlaby** [comment]
same in 1065

**Comment by JaroslawSlaby** [comment]
1117

**Comment by JaroslawSlaby** [comment]
and other. look at this

**Comment by boczkas** [comment]
Fixed ones which I've found
