### ISSUE TITLE
Powtórzony kod

### ISSUE THREAD

**Issue by AdrianHarenczyk** [boczkas/assertTest#17]
https://github.com/boczkas/assertTest/blob/301c182092902f86936d182929e8fe5a3555151b/src/test/java/TestArrayList.java#L613

Dodawanie jeszcze raz elementów które są w metodzie wyżej. Te z metody wyżej nie mogły być użyte z racji niezmienności listy która jest przez Nią zwracana.

**Comment by boczkas** [comment]
Prawda, zacząłem działać w tym temacie. Praca trwa
