### ISSUE TITLE
Nazwa klasy testowej

### ISSUE THREAD

**Issue by AdrianHarenczyk** [boczkas/assertTest#8]
https://github.com/boczkas/assertTest/blob/301c182092902f86936d182929e8fe5a3555151b/src/test/java/TestArrayList.java#L9

Nazwa klasy testowej powinna nie zawierać pojedynczej implementacji interface'u list, informować ogólnie o testowaniu właśnie tego interface'u w przypadku testowania dwóch różnych implementacji.

**Comment by boczkas** [comment]
Super komentarz, dzięki wielkie.
Zaraz poprawię.
